backups-limit: 15
repos:
  - git-origin: github
    organization: foxleren
    repository: git-backup
    branch: master
    backups-limit: 10
  - git-origin: github
    organization: foxleren
    repository: notes
    branch: master
  - git-origin: github
    organization: onyxdb
    repository: onyxdb
    branch: master
  - git-origin: github
    organization: onyxdb
    repository: internal-docs
    branch: master
  - git-origin: github
    organization: onyxdb
    repository: mongodb-kubernetes-operator
    branch: master
  - git-origin: github
    organization: foxleren
    repository: tinkoff-sre
    branch: master
    backups-limit: 5
  - git-origin: github
    organization: xority-space
    repository: xority-snapshot-19-10-2024
    branch: master
    backups-limit: 5
