backups-limit: 10
repos:
  - git-origin: github
    organization: foxleren
    repository: git-backup
    branch: master
    backups-limit: 3
  - git-origin: github
    organization: foxleren
    repository: notes
    branch: master
  - git-origin: github
    organization: onyxdb
    repository: onyxdb
    branch: master
  - git-origin: github
    organization: foxleren
    repository: tinkoff-sre
    branch: master
    backups-limit: 3
  - git-origin: github
    organization: xority
    repository: xority-snapshot-19-10-2024
    branch: master
    backups-limit: 3
